# Generated by Django 4.2.3 on 2023-08-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompasParser', '0002_alter_keywordbag_bag1_alter_keywordbag_bag2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordbag',
            name='bag2',
            field=models.TextField(blank=True, default='Марий Эл,Йошкар-Ол,РМЭ,марийская,йошкаролинец,йошкаролинка,йошкаролин'),
        ),
    ]
