# Generated by Django 4.2.3 on 2023-10-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompasParser', '0003_alter_keywordbag_bag2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='parsednews',
            name='comments',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parsednews',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parsednews',
            name='reposts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
