# Generated by Django 4.2.3 on 2023-10-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompasParser', '0004_parsers_parsednews_comments_parsednews_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsednews',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
