# Generated by Django 4.2.3 on 2023-10-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompasParser', '0006_alter_parsednews_comments_alter_parsednews_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsednews',
            name='url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parsednews',
            name='comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parsednews',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parsednews',
            name='reposts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parsednews',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
