# Generated by Django 4.2.3 on 2023-10-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompasParser', '0007_parsednews_url_alter_parsednews_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='parser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CompasParser.parsers'),
            preserve_default=False,
        ),
    ]
