# Generated by Django 4.2.3 on 2023-10-12 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CompasParser', '0008_newssource_parser'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsers',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newssource',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
