# Generated by Django 4.2.3 on 2023-10-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompasParser', '0009_parsers_user_alter_newssource_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newssource',
            old_name='url',
            new_name='rss_url',
        ),
        migrations.RemoveField(
            model_name='parsednews',
            name='url',
        ),
    ]
