# Generated by Django 4.2.3 on 2023-10-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompasParser', '0010_rename_url_newssource_rss_url_remove_parsednews_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
