# Generated by Django 4.2.3 on 2023-10-12 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CompasParser', '0011_newssource_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_app_token', models.CharField(blank=True, max_length=50, null=True)),
                ('vk_app_id', models.CharField(blank=True, max_length=50, null=True)),
                ('vk_app_secret', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram_api_id', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram_api_hash', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
