# Generated by Django 4.2.3 on 2023-10-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompasParser', '0012_socialdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='members_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='owner',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
