# Generated by Django 4.2.3 on 2023-10-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompasParser', '0013_newssource_members_count_newssource_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='rss_url',
            field=models.URLField(null=True),
        ),
    ]
