# Generated by Django 4.2.3 on 2023-10-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompasParser', '0014_alter_newssource_rss_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='members_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='rss_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialdata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
