# Generated by Django 4.2.3 on 2023-10-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompasParser', '0015_alter_newssource_members_count_alter_newssource_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialdata',
            name='telegram_api_hash',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='socialdata',
            name='telegram_api_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='socialdata',
            name='vk_app_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='socialdata',
            name='vk_app_secret',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='socialdata',
            name='vk_app_token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
