# Generated by Django 4.2.6 on 2023-12-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompasParser', '0017_alter_keywordbag_options_alter_newssource_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='owner',
            field=models.CharField(blank=True, null=True),
        ),
    ]
