# Generated by Django 4.2.6 on 2024-02-19 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CompasParser', '0019_monitoringoperatorrole'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonitoringOperatorRole',
            new_name='EconomMonitoringOperatorRole',
        ),
        migrations.AlterModelOptions(
            name='econommonitoringoperatorrole',
            options={'permissions': [('can_export_to_word', 'Can export data to Word')], 'verbose_name': 'РОЛЬ_ОПЕРАТОР_ЭКОНОМ', 'verbose_name_plural': 'РОЛЬ_ОПЕРАТОР_ЭКОНОМ'},
        ),
        migrations.CreateModel(
            name='PressMonitoringOperatorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'РОЛЬ_ОПЕРАТОР_СМИ',
                'verbose_name_plural': 'РОЛЬ_ОПЕРАТОР_СМИ',
                'permissions': [('can_export_to_excel', 'Can export data to Excel')],
            },
        ),
    ]
