# Generated by Django 4.2.6 on 2024-02-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompasParser', '0020_rename_monitoringoperatorrole_econommonitoringoperatorrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordbag',
            name='bag_arch',
            field=models.TextField(blank=True),
        ),
    ]
