"""
Django settings for DailyParser project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SESSION_COOKIE_NAME = 'compasnews_session'
SESSION_COOKIE_PATH = '/compasnews/'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o@7t#l$o$n7%nqhn(8%(740ryg_=*l4mmye8e(4*kn438)#vx*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ORIGIN_WHITELIST = (
    'localhost:9000',
    'compas.cbmari.ru',
)

CSRF_TRUSTED_ORIGINS = ['http://localhost:9000', 'https://compas.cbmari.ru']

# Application definition
INSTALLED_APPS = [
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'CompasParser',

    # ...
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.nextcloud',
    'allauth.socialaccount.providers.google',
    # ...
    "allauth_ui",
    "widget_tweaks",
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'CompasParser.middleware.Funny502ErrorMiddleware',
]

ROOT_URLCONF = 'Parser.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

##
#LOGIN_REDIRECT_URL = "parsed_news"
LOGIN_REDIRECT_URL = "/compasnews/parsed_news"
ACCOUNT_LOGOUT_ON_GET = True
##
SOCIALACCOUNT_PROVIDERS = {
    'nextcloud': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'SERVER': 'https://cl.cbmari.ru/',
        'APP': {
            'client_id': 'nGJxerRYWBfXssqj2Qn23vCaLbsXNjLJXycmOrC9EKjJjMHLJ1nSPUbpFKp9Xa7m',
            'secret': '3TUtTx9oq5GKxY24erQBqMwyBbx5pOzC44OQxLTCDa3imUMQDGLA20C7ucELPFS0',
            'key': '',
        }
    },
    'google': {
        'APP': {
            'client_id': '651295796869-kps54tfeqg93qoko321mpl6ur411q159.apps.googleusercontent.com',
            'secret': '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',
            'key': '',
        }
    }
}
ACCOUNT_LOGIN_TEMPLATE = 'account/login.html'
ACCOUNT_DEFAULT_HTTP_PROTOCOL='https'
ACCOUNT_EMAIL_VERIFICATION = 'none'

WSGI_APPLICATION = 'Parser.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }    
    'default': {
        'ENGINE': 'django.db.backends.postgresql', # Движок для PostgreSQL
        'NAME': 'compasnews',                      # Имя вашей базы данных
        'USER': 'jupyhub',                         # Имя пользователя PostgreSQL
        'PASSWORD': 'Jupy_1569',                   # Пароль пользователя
        'HOST': 'office.cbmari.ru',                # Адрес сервера базы данных. Обычно 'localhost', если база данных находится на том же сервере, где и Django.
        'PORT': '5432',                            # Порт, на котором работает PostgreSQL. Обычно 5432.
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/compas/static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



LOGGING_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGGING_DIR):
    os.makedirs(LOGGING_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGGING_DIR, 'error.log'),
        },
    },
    'root': {
        'handlers': ['file'],
        'level': 'ERROR',
    },
}













# # ЭЛАСТИКСЕРЧ
# ELASTICSEARCH_DSL = {
#     'default': {
#         'hosts': 'http://localhost:9200',
#     },
# }